services:
  web:
    build: .
    container_name: pembau-website
    restart: unless-stopped
    expose: 
      - 80
    environment:
      VIRTUAL_HOST: pembau.art,www.pembau.art
      LETSENCRYPT_HOST: pembau.art,www.pembau.art
    networks:
      - infra_proxy

networks:
  infra_proxy:
    external: true
